' Gambas module file

' dfhLog- Hamradio LogBook
'     Copyright (C) 2009  Jesús Guardón, EA7DFH <ea7dfh@gmail.com>
'
'     This program is free software: you can redistribute it and/or modify
'     it under the terms of the GNU General Public License as published by
'     the Free Software Foundation, either version 3 of the License, or
'     (at your option) any later version.
'
'     This program is distributed in the hope that it will be useful,
'     but WITHOUT ANY WARRANTY; without even the implied warranty of
'     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
'     GNU General Public License for more details.
'
'     You should have received a copy of the GNU General Public License
'     along with this program.  If not, see <http://www.gnu.org/licenses/>.

Public cnLog As Connection

Public Function connDB(path As String) As Boolean

    Dim myHost, myDBName As String

    myHost = Left(path, RInStr(path, "/"))
    myDBName = Right(path, Len(path) - RInStr(path, "/"))
    '     DEBUG myHost;; myDBName
    If cnLog <> Null Then Return False

    cnLog = New Connection

    cnLog.Host = myHost
    cnLog.Name = myDBName
    cnLog.Type = "sqlite3"
    Try cnLog.Open()

    If Error Then
        cnLog = Null
        Message.Error(("Error connecting to database: ") & myDBName & "\n" & Error.Text)
        Return True
    Endif

    Return False

End

Public Sub CloseDB()

    If cnLog = Null Then Return
    cnLog.Close()
    cnLog = Null

End
